In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso, RidgeCV, LassoCV, ElasticNet, ElasticNetCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import seaborn as sns

C:\Users\RAKSHANDA\anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py:7: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import (to_datetime, Int64Index, DatetimeIndex, Period,
C:\Users\RAKSHANDA\anaconda3\lib\site-packages\statsmodels\tsa\base\tsa_model.py:7: FutureWarning: pandas.Float64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import (to_datetime, Int64Index, DatetimeIndex, Period,


In [2]:
df = pd.read_csv('Admission_Prediction .csv')

In [3]:
pf = ProfileReport(df)

In [4]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [5]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [6]:
df['GRE Score'] = df['GRE Score'].fillna(df['GRE Score'].mean())

In [7]:
df['TOEFL Score'] = df['TOEFL Score'].fillna(df['TOEFL Score'].mean())

In [8]:
df['University Rating'] = df['University Rating'].fillna(df['University Rating'].mean())

In [9]:
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  500.000000   500.000000         500.000000  500.000000   
mean   250.500000  316.558763   107.187755           3.121649    3.374000   
std    144.481833   11.103952     6.051338           1.128802    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  309.000000   103.000000           2.000000    2.500000   
50%    250.500000  316.558763   107.000000           3.000000    3.500000   
75%    375.250000  324.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

             LOR        CGPA    Research  Chance of Admit  
count  500.00000  500.000000  500.000000        500.00000  
mean     3.48400    8.576440    0.560000          0.72174  
std      0.92545    0.604813    0.496884          0.14114  
min      1.00000    6.800000    0.000000          0.34000  
25%      3.00000    8.127500    0.000000          0.63000  
50%      3.50000    8.560000    1.000000          0.72000  
75%      4.00000    9.040000    1.000000          0.82000  
max      5.00000    9.920000    1.000000          0.97000

In [10]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [11]:
df.drop(columns = ['Serial No.'], inplace = True)

In [12]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [13]:
y = df['Chance of Admit']

In [14]:
x = df.drop(columns= ['Chance of Admit'])

In [15]:
x

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

In [16]:
# Dataset values are varing a lot
# so bring it down to lower scale without changing a meaning
# use standard scalar
# mean = 0 and std dev = 1

In [17]:
scaler = StandardScaler()

In [19]:
arr = scaler.fit_transform(x)

In [20]:
df1 = pd.DataFrame(arr)

In [46]:
pf1 = ProfileReport(df1)
pf1.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [21]:
df1.describe()

0             1             2             3             4  \
count  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02   
mean   4.350520e-15  9.419132e-16  5.608847e-16  2.926548e-16 -1.332268e-17   
std    1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00   
min   -2.394225e+00 -2.512331e+00 -1.881441e+00 -2.397950e+00 -2.686789e+00   
25%   -6.814090e-01 -6.927310e-01 -9.946589e-01 -8.828175e-01 -5.235128e-01   
50%    5.124333e-15 -3.105811e-02 -1.078766e-01  1.272712e-01  1.730621e-02   
75%    6.708143e-01  7.960330e-01  7.789057e-01  6.323155e-01  5.581253e-01   
max    2.113186e+00  2.119379e+00  1.665688e+00  1.642404e+00  1.639763e+00   

                  5             6  
count  5.000000e+02  5.000000e+02  
mean   3.091971e-15 -2.202682e-16  
std    1.001002e+00  1.001002e+00  
min   -2.940115e+00 -1.128152e+00  
25%   -7.430227e-01 -1.128152e+00  
50%   -2.720919e-02  8.864053e-01  
75%    7.672196e-01  8.864053e-01  
max    2.223672e+00  8.864053e-01

In [22]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [23]:
arr.shape

(500, 7)

In [24]:
vif_df = pd.DataFrame()

vif_df['vif'] = [variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

vif_df['feature'] = x.columns

In [25]:
vif_df

vif            feature
0  4.153268          GRE Score
1  3.792866        TOEFL Score
2  2.508768  University Rating
3  2.775750                SOP
4  2.037308                LOR
5  4.651670               CGPA
6  1.459311           Research

In [26]:
arr

array([[ 1.84274116e+00,  1.78854223e+00,  7.78905651e-01, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [ 6.70814288e-01, -3.10581135e-02,  7.78905651e-01, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [ 5.12433309e-15, -5.27312752e-01, -1.07876604e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.21170361e+00,  2.11937866e+00,  1.66568791e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 9.41258951e-01,  9.61451165e-01,  7.78905651e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [94]:
x_train , x_test, y_train , y_test = train_test_split(arr, y, test_size = 0.25, random_state=100)

In [95]:
x_train

array([[-0.41096436, -0.52731275, -0.1078766 , ...,  0.01730621,
        -0.25891759, -1.12815215],
       [ 0.12992496, -0.19647633, -0.1078766 , ..., -0.52351283,
         0.12174622, -1.12815215],
       [-1.13215013, -1.02356739, -0.99465886, ..., -1.06433187,
        -1.51676323, -1.12815215],
       ...,
       [-1.04200191, -0.85814918, -0.99465886, ..., -1.06433187,
        -0.65613201, -1.12815215],
       [-0.50111259, -0.85814918, -0.1078766 , ...,  0.55812525,
         0.10519562,  0.88640526],
       [-1.31244657, -0.85814918, -1.88144112, ..., -2.14596996,
        -0.95404281, -1.12815215]])

In [96]:
lr = LinearRegression()

In [97]:
lr.fit(x_train, y_train)

LinearRegression()

In [98]:
pickle.dump(lr, open('addmission_lr_model.pickle', 'wb'))

In [99]:
model = pickle.load(open('addmission_lr_model.pickle', 'rb'))

In [100]:
model.predict(test1)

array([0.95359739])

In [101]:
# First u have to transform the test  dataset 
# 

In [102]:
test1 = scaler.transform([[337.000000,118.0,4.0,4.5,4.5,9.65,1]])

In [103]:
# we cant use directly
#lr.predict([[337.000000,118.0,4.0,4.5,4.5,9.65,1]])

In [104]:
lr.predict(test1)

array([0.95359739])

In [105]:
lr.score(x_test, y_test)

0.8262844735686963

In [106]:
# IF u change the random state and test size percent u r accracy will get increase

In [107]:
# Adjusted R-Square

def adj_r2(x,y):
    r2 = lr.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [108]:
adj_r2(x_test,y_test)

0.8158912369446012

In [109]:
lr.coef_

array([0.015458  , 0.01908417, 0.00381077, 0.00315846, 0.01678637,
       0.07622763, 0.01400522])

In [110]:
lr.intercept_

0.7181156002659718

In [111]:
lassocv = LassoCV(alphas=None,cv=5, max_iter=2000000, normalize=True)
lassocv.fit(x_train, y_train)

LassoCV(cv=5, max_iter=2000000, normalize=True)

In [112]:
lassocv.alpha_

2.7745719225519405e-05

In [113]:
lasso = Lasso(alpha= lassocv.alpha_)
lasso.fit(x_train, y_train)

Lasso(alpha=2.7745719225519405e-05)

In [114]:
lasso.score(x_test, y_test)

0.826321706823379

In [115]:
ridgecv = RidgeCV(alphas= np.random.uniform(0,10,50), cv =10 , normalize=True)
ridgecv.fit(x_train,y_train)

RidgeCV(alphas=array([6.7121389 , 5.72342061, 2.84508041, 8.71279717, 9.78131795,
       5.18691299, 6.37272459, 2.01722871, 7.63553364, 6.77152292,
       2.74678206, 4.29485844, 2.66238269, 4.61303299, 8.30827812,
       4.57395331, 0.3367994 , 2.91154887, 7.01004878, 6.59635282,
       3.28604611, 2.33203481, 5.94428018, 8.66453642, 4.44694813,
       9.05145509, 4.38613922, 1.93599669, 6.65207046, 6.04620124,
       4.88184182, 6.68832448, 4.82484113, 6.1086169 , 4.25422002,
       7.70951245, 5.16663952, 6.14273909, 4.44024985, 9.4642602 ,
       9.01795594, 7.25567948, 7.35874226, 5.56937837, 6.38736935,
       3.05784953, 0.90555562, 4.23119318, 5.65909485, 0.59805193]),
        cv=10, normalize=True)

In [116]:
ridgecv.alpha_

0.33679940155950105

In [117]:
ridge_lr = Ridge(alpha = ridgecv.alpha_)
ridge_lr.fit(x_train, y_train)

Ridge(alpha=0.33679940155950105)

In [118]:
ridge_lr.score(x_test,y_test)

0.8263978263623718

In [119]:
elastic = ElasticNetCV(alphas=None , cv =10)
elastic.fit(x_train,y_train)

ElasticNetCV(cv=10)

In [120]:
elastic.alpha_

0.00032049828688228085

In [121]:
elastic.l1_ratio

0.5

In [122]:
elastic_lr = ElasticNet(alpha=elastic.alpha_, l1_ratio=elastic.l1_ratio)

In [123]:
elastic_lr.fit(x_train,y_train)

ElasticNet(alpha=0.00032049828688228085)

In [124]:
elastic_lr.score(x_test,y_test)

0.8265118379982933