In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.metrics import accuracy_score , confusion_matrix , roc_auc_score , roc_curve
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/aniruddhachoudhury/Red-Wine-Quality/master/winequality-red.csv")

In [3]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [4]:
x_train , x_test, y_train,y_test = train_test_split(x,y,random_state = 20)

In [5]:
knn = KNeighborsClassifier()

In [6]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [7]:
knn.score(x_test,y_test)

0.5175

In [8]:
param = {
    'n_neighbors':[3,5,7,9,12,13,15,17,21],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size' : [10 , 15 , 20 , 25 , 30 , 35 , 45 , 50 ],
    'p' : [1,2],
    'weights' : ['uniform', 'distance']
}

In [9]:
grid_cv = GridSearchCV(knn,param_grid=param )

In [10]:
#grid_cv.fit(x_train, y_train)
#grid_cv.best_params_

In [11]:
knn = KNeighborsClassifier(n_neighbors=21,p= 1 ,weights='distance' , leaf_size=10 , algorithm='auto')

In [12]:
knn.fit(x_train,y_train)

KNeighborsClassifier(leaf_size=10, n_neighbors=21, p=1, weights='distance')

In [13]:
knn.score(x_test,y_test)

0.6325

In [14]:
import pickle

In [15]:
pickle.dump(knn, open('knn.pkl', 'wb'))

In [16]:
knn1 = KNeighborsClassifier()

In [17]:
knn1.fit(x_train,y_train)

KNeighborsClassifier()

In [18]:
pickle.dump(knn1,open("knn1.pkl", 'wb'))

In [19]:
#knn stores entire data instead of object

In [20]:
# train and test complexity is increase

In [21]:
knn.predict(x_test)

array([6, 5, 5, 5, 5, 6, 5, 6, 5, 6, 6, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 6,
       6, 5, 7, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 7, 6, 5, 6, 6, 5, 5, 6, 5,
       7, 5, 6, 6, 6, 6, 7, 5, 5, 5, 6, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5,
       5, 5, 6, 6, 5, 6, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5,
       5, 5, 5, 6, 5, 6, 6, 6, 5, 6, 7, 5, 5, 5, 6, 6, 6, 6, 6, 5, 5, 6,
       5, 6, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 6, 7, 6, 5,
       5, 6, 6, 5, 6, 6, 5, 7, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 5, 5, 6,
       6, 6, 5, 5, 5, 6, 6, 6, 6, 6, 5, 7, 5, 5, 5, 5, 5, 6, 5, 6, 6, 6,
       6, 6, 5, 5, 7, 6, 7, 5, 5, 6, 5, 5, 6, 5, 6, 5, 6, 6, 5, 7, 5, 6,
       6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 5, 5, 6, 5, 6, 5, 5, 5,
       5, 5, 5, 6, 6, 7, 5, 6, 7, 6, 5, 5, 7, 6, 5, 5, 6, 6, 6, 5, 6, 7,
       7, 5, 6, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 6, 7, 5, 5, 6, 6, 5, 5, 5,
       6, 6, 6, 7, 5, 5, 5, 7, 7, 6, 5, 7, 6, 5, 6, 5, 6, 6, 6, 5, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 7, 7, 5, 5, 5, 6, 5, 5,

In [22]:
knn.predict([x_test.iloc[0]])

array([6], dtype=int64)

# SVM

In [23]:
from sklearn.svm import SVC

In [24]:
svc = SVC()

In [25]:
svc.fit(x_train,y_train)

SVC()

In [26]:
svc.score(x_test,y_test)

0.5

In [33]:
#Kernal -  rbf - radial bias func = trying to derive one more stat
# Gamma is parameter to control the third parameter

In [34]:
param ={"kernel":['linear', 'poly', 'rbf', 'sigmoid' ],
        'C':[.1,.4 , .6 , 1,2,3,100,200,500],
        'gamma':[.001,.1,.4,.004,.003]
    } 
#svm_grid = GridSearchCV(svc , param_grid=param , verbose=3 )
#svm_grid.fit(x_train,y_train)

In [35]:
#svm_grid.best_params_

In [36]:
svc1 = SVC(kernel='poly')
svc1.fit(x_train,y_train)

SVC(kernel='poly')

In [37]:
svc1.score(x_test,y_test)

0.49

# SVR

In [39]:
df = pd.read_csv('Admission_Prediction .csv')

In [56]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [57]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=30)

In [58]:
from sklearn.svm import SVR

In [59]:
svr = SVR()

In [60]:
df.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [61]:
df['GRE Score'] = df['GRE Score'].fillna(df['GRE Score'].mean())

In [62]:
df['TOEFL Score'] =df['TOEFL Score'].fillna(df['TOEFL Score'].mean())

In [63]:
df['University Rating'] = df['University Rating'].fillna(df['University Rating'].mean())

In [64]:
df

Serial No.   GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1  337.000000        118.0                4.0  4.5  4.5  9.65   
1             2  324.000000        107.0                4.0  4.0  4.5  8.87   
2             3  316.558763        104.0                3.0  3.0  3.5  8.00   
3             4  322.000000        110.0                3.0  3.5  2.5  8.67   
4             5  314.000000        103.0                2.0  2.0  3.0  8.21   
..          ...         ...          ...                ...  ...  ...   ...   
495         496  332.000000        108.0                5.0  4.5  4.0  9.02   
496         497  337.000000        117.0                5.0  5.0  5.0  9.87   
497         498  330.000000        120.0                5.0  4.5  5.0  9.56   
498         499  312.000000        103.0                4.0  4.0  5.0  8.43   
499         500  327.000000        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [65]:
svr.fit(x_train,y_train)

SVR()

In [66]:
svr.score(x_test,y_test)

0.6241120903422273

In [67]:
from sklearn.metrics import r2_score
r2_score(y_test ,  svr.predict(x_test))

0.6241120903422273

In [68]:
svr.predict([x.iloc[0]])

array([0.78212365])

In [71]:
y[0]

0.92

# Stacking

In [72]:
import pandas as pd 
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [73]:
data = pd.read_csv("https://raw.githubusercontent.com/aniruddhachoudhury/Red-Wine-Quality/master/winequality-red.csv")

In [80]:
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [90]:
# divide data into two division

train, val_train , test, val_test = train_test_split(x,y,test_size=.50,random_state=30)

In [91]:
x_train , x_test , y_train, y_test = train_test_split(train ,test,random_state = 30 , test_size = .20)

In [92]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [93]:
knn.score(x_test,y_test)

0.54375

In [94]:
svc = SVC()
svc.fit(x_train,y_train)

SVC()

In [95]:
svc.score(x_test,y_test)

0.4875

In [97]:
predcition_knn = knn.predict(val_train)
prediction_svc = svc.predict(val_train)

In [98]:
input3 = np.column_stack((predcition_knn,prediction_svc))

In [99]:
output = val_test

In [100]:
pd.DataFrame(input3)

0  1
0    7  6
1    5  6
2    6  6
3    5  6
4    5  6
..  .. ..
795  5  6
796  5  6
797  5  6
798  6  6
799  5  5

[800 rows x 2 columns]

In [101]:
rf = RandomForestClassifier()

In [102]:
rf.fit(input3,output)

RandomForestClassifier()

In [104]:
knn_output = knn.predict(x_test)
svc_output = svc.predict(x_test)

In [105]:
output_stack1 = np.column_stack ((knn_output,svc_output))

In [106]:
rf.predict(output_stack1)

array([5, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 5, 6, 5, 6,
       6, 5, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 5,
       6, 6, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 5, 6, 6, 5,
       5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5,
       6, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6, 5, 5, 6, 6, 5,
       5, 6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5,
       6, 6, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6,
       5, 5, 5, 6, 5, 5], dtype=int64)

In [107]:
rf.score(output_stack1 , y_test)

0.55